if (NOT CMAKE_BUILD_TYPE STREQUAL "Release")
  find_program(CLANGTIDY clang-tidy)
  if (CLANGTIDY)
    message(STATUS "Using clang-tidy")
    set(CMAKE_CXX_CLANG_TIDY "${CLANGTIDY};-extra-arg=-Wno-unknown-warning-option")
    # Explicitly enable exceptions on Windows
    if (WIN32)
      set(CMAKE_CXX_CLANG_TIDY "${CMAKE_CXX_CLANG_TIDY};--extra-arg=/EHsc")
    endif ()
  else ()
    message(WARNING "clang-tidy requested but executable not found")
  endif ()

    if(MSVC)
        message(STATUS "Using address sanitizer")
        add_compile_options("/fsanitize=address")
        add_compile_definitions(_DISABLE_VECTOR_ANNOTATION _DISABLE_STRING_ANNOTATION)
    endif ()
endif ()